# Generated by Django 2.1.2 on 2018-10-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalleave',
            name='leave_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalleave',
            name='leave_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
